package com.example.user.fahacalculator.common;

public enum Buttons {
    PLUS_BUTTON, MINUS_BUTTON, MULTIPL_BUTTON, DIVISION_BUTTON, DEL_BUTTON, DOT_BUTTON, EQUAL_BUTTON, ROOT_BUTTON, SQUARE_BUTTON, DOUBLE_ZERO_BUTTON, OPEN_BRACKETS_BUTTON, CLOSE_BRACKETS_BUTTON
}
